In [1]:
import numpy as np

In [2]:
int_array=np.arange(20)
int_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
secint_arr=np.arange(30,50)
secint_arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [4]:
thrint_arr=np.arange(100,200,5)
thrint_arr

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [5]:
floats_arr=np.linspace(1,10)
floats_arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [6]:
first_rand_arr=np.random.rand(5)
first_rand_arr

array([0.03102535, 0.91017281, 0.92352806, 0.16284629, 0.76606848])

In [7]:
sec_rand_arr=np.random.rand(5,5)
sec_rand_arr


array([[0.24455195, 0.32498099, 0.26467511, 0.21870072, 0.78102441],
       [0.65145759, 0.17395948, 0.07892812, 0.55376643, 0.50389998],
       [0.80870039, 0.77160665, 0.21424295, 0.67380955, 0.92909799],
       [0.46738808, 0.97549757, 0.04761476, 0.05974002, 0.20004338],
       [0.01541737, 0.85228696, 0.72302046, 0.3694571 , 0.91194275]])