In [1]:
print("hello numpy")

hello numpy


In [2]:
45+6+9


60

In [3]:
import numpy as np

In [6]:
i = np.array([4,5,6,7,1])

In [7]:
print (i)

[4 5 6 7 1]


In [13]:
i[4]

1

In [14]:
i[4]=8
i

array([4, 5, 6, 7, 8])

In [21]:
numz=np.array([[1,2,3,4,5],[9,8,7,6,5]])
numz

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5]])

In [22]:
numz.ndim

2

In [23]:
numz[0,2]

3

In [24]:
listone = [2,4,6,8,10]
listone

[2, 4, 6, 8, 10]

In [25]:
new_array=np.array(listone)

In [27]:
new_array

array([ 2,  4,  6,  8, 10])

In [28]:
new_array.dtype

dtype('int32')